# Generated by Django 2.0.4 on 2018-04-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureAirportIataCode', models.CharField(max_length=5)),
                ('outboundDepartureDateFrom', models.DateField()),
                ('outboundDepartureDateTo', models.DateField()),
                ('inboundDepartureDateFrom', models.DateField()),
                ('inboundDepartureDateTo', models.DateField()),
            ],
        ),
    ]
