# Generated by Django 2.0.4 on 2018-04-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel0', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='inboundDepartureDateFrom',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='inboundDepartureDateTo',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='outboundDepartureDateFrom',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='outboundDepartureDateTo',
        ),
    ]
