# Generated by Django 2.0.4 on 2018-05-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel0', '0002_auto_20180430_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flights',
            options={'verbose_name_plural': 'Flights'},
        ),
    ]
