# Generated by Django 2.0.5 on 2018-05-04 17:57

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Travel0', '0003_auto_20180501_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='departureAirportIataCode',
        ),
        migrations.AddField(
            model_name='flights',
            name='inboundDepartureDateFrom',
            field=models.DateField(default=datetime.datetime(2018, 5, 4, 17, 57, 8, 418405)),
        ),
        migrations.AddField(
            model_name='flights',
            name='inboundDepartureDateTo',
            field=models.DateField(default=datetime.datetime(2018, 5, 4, 17, 57, 8, 418405)),
        ),
        migrations.AddField(
            model_name='flights',
            name='outboundDepartureAirportIataCode',
            field=models.CharField(default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flights',
            name='outboundDepartureDateFrom',
            field=models.DateField(default=datetime.datetime(2018, 5, 4, 17, 57, 8, 418405)),
        ),
        migrations.AddField(
            model_name='flights',
            name='outboundDepartureDateTo',
            field=models.DateField(default=datetime.datetime(2018, 5, 4, 17, 57, 8, 418405)),
        ),
    ]
