# Generated by Django 2.0.5 on 2018-05-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel0', '0004_auto_20180504_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='inboundDepartureDateFrom',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='inboundDepartureDateTo',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='outboundDepartureDateFrom',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='outboundDepartureDateTo',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
